### ISSUE TITLE
One click install link

### ISSUE THREAD

**Issue by prakharb5** [RDIL/Classroom-Dark#1]
Please make a one-click install link for this theme. I would be very grateful for the same.

**Comment by RDIL** [comment]
I don't believe this is possible for stylus stylesheets.  I was considering making this into a browser extension, which I may do soon.

**Comment by prakharb5** [comment]
It is quite possible to make it a stylus design. Pls don't make a separate extension.

Have a look at other themes for Telegram web or whatsapp web on GitHub. You can follow from them and can maybe work it out 😁

**Comment by RDIL** [comment]
Interesting!  I'll take a look.  Thanks!

**Comment by RDIL** [comment]
I have added support for installing with one-click.  See the readme.

I don't have much experience with stylus, and I want to experiment more in the coming days.

Thanks for the feedback!

**Comment by prakharb5** [comment]
Thank you!
